# Generated by Django 3.1.5 on 2021-03-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empresa',
        ),
    ]
